trigger: none

parameters:
  - name: environment
    default: test
  - name: variableGroupName
    default: app-infra-library
  - name: agentPool
    default: SelfHosted

extends:
    template: templates/deploy-infra.yml
    parameters:
      environment: ${{ parameters.environment }}
      variableGroupName: ${{ parameters.variableGroupName }}
      agentPool: ${{ parameters.agentPool }}
      terraformVersion: "1.3.5"